
#include <Lib/Lib.h>
#include <Lib/DataBlock/DataBlock.h>
#include <Lib/StdString/StdString.h>

#include <fstream>
#include <string>
using namespace std;

#define VERSION "v0.3"

int main( int argc, char* argv[] ) {
	if ( argc < 3 ) {
		printf( "Text2C " VERSION " - Convert a Text file to a C file, and append a null terminator (0)\n" );
		printf( "  Usage: Text2C In.txt Out.c SUFFIX PREFIX\n" );
		return -1;
	}

	// Load File //
	DataBlock* File = new_read_DataBlock( argv[1] );
	
	string Prefix("");
	string Suffix("");
	
	if ( argc > 3 ) {
		Suffix = argv[3];
	}
	
	if ( argc > 4 ) {
		Prefix = argv[4];
	}

	string FileName = Gel::String::GetFileName( Gel::String::SystemSlash( argv[1] ) );
	string BaseName = Gel::String::GetBaseName( FileName );
	string Symbol = Prefix + BaseName + Suffix;
	
	// Open Output File //
	ofstream Out( argv[2] );
	
	Out << "// " << Symbol << " (" << FileName << ") - Generated by Text2C " VERSION " //" << endl;
	Out << "extern const unsigned " << Symbol << "_Size;" << endl;
	Out << "const unsigned " << Symbol << "_Size = " << (File->Size) << "+1;" << endl;
	Out << endl;
	Out << "extern const char " << Symbol << "[];" << endl;
	Out << "const char " << Symbol << "[] = {";
	
	int NextLine = 0;
	for ( int idx = 0; idx < File->Size; idx++ ) {
		if ( NextLine-- == 0 ) {
			NextLine = 16;
			Out << "\n\t";			
		}
		
		if ( File->Data[idx] >= 32 ) {
			if ( File->Data[idx] == '\'' ) {		// single quote //
				Out << (int)File->Data[idx] << ", ";
			}
			else if ( File->Data[idx] == 127 ) {	// del character //
				Out << (int)File->Data[idx] << ", ";
			}
			else if ( File->Data[idx] == 255 ) {	// last character //
				Out << (int)File->Data[idx] << ", ";
			}
			else {
				Out << "'" << (char)File->Data[idx] << "', ";
			}
		}
		else {
			Out << (int)File->Data[idx] << ", ";
		}
	}

	Out << "0";
	
	Out << endl << "};" << endl;
		
	// Close Output File //
	Out.close();
	
	// Done with File //
	delete_DataBlock(File);

	return 0;	
}
