
#include <Lib/Lib.h>
#include <Lib/DataBlock/DataBlock.h>
#include <Lib/StdString/StdString.h>

#include <fstream>
#include <string>
using namespace std;

#define VERSION "v0.2"

int main( int argc, char* argv[] ) {
	if ( argc < 3 ) {
		printf( "Bin2C " VERSION " - Convert a Binary file to a C file\n" );
		printf( "  Usage: Bin2C In.bin Out.c SUFFIX PREFIX\n" );
		return -1;
	}

	// Load File //
	DataBlock* File = new_read_DataBlock( argv[1] );
	
	string Prefix("");
	string Suffix("");
	
	if ( argc > 3 ) {
		Suffix = argv[3];
	}

	if ( argc > 4 ) {
		Prefix = argv[4];
	}
	
	string FileName = Gel::String::GetFileName( Gel::String::SystemSlash( argv[1] ) );
	string BaseName = Gel::String::GetBaseName( FileName );
	string Symbol = Prefix + BaseName + Suffix;
	
	// Open Output File //
	ofstream Out( argv[2] );
	
	Out << "// " << Symbol << " (" << FileName << ") - Generated by Bin2C " VERSION " //" << endl;
	Out << "extern const unsigned " << Symbol << "_Size;" << endl;
	Out << "const unsigned " << Symbol << "_Size = " << (File->Size) << ";" << endl;
	Out << endl;
	Out << "extern const char " << Symbol << "[];" << endl;
	Out << "const char " << Symbol << "[] = {";
	
	int NextLine = 0;
	for ( int idx = 0; idx < File->Size; idx++ ) {
		if ( NextLine-- == 0 ) {
			NextLine = 16;
			Out << "\n\t";			
		}
		
		Out << (int)File->Data[idx] << ", ";
	}
	
	Out << endl << "};" << endl;
	
	
	// Close Output File //
	Out.close();
	
	// Done with File //
	delete_DataBlock(File);

	return 0;	
}
