
#include <Style/Log.h>
#include <Core/DataBlock.h>

#include <fstream>
#include <string>
#include <Util/String/String.h>
using namespace std;

#define VERSION "v0.2"

int main( int argc, char* argv[] ) {
	if ( argc < 3 ) {
		Log( "Bin2C " VERSION " - Convert a Binary file to a C file\n" );
		Log( "  Usage: Bin2C In.bin Out.c PREFIX SUFFIX\n" );
		return -1;
	}

	// Load File //
	DataBlock* File = new_read_DataBlock( argv[1] );
	
	string Prefix("");
	string Suffix("");
	
	if ( argc > 3 ) {
		Prefix = argv[3];
	}

	if ( argc > 4 ) {
		Suffix = argv[4];
	}
	
	string FileName = String::FileName( String::SystemSlash( argv[1] ) );
	string BaseName = String::BaseName( FileName );
	string Symbol = Prefix + BaseName + Suffix;
	
	// Open Output File //
	ofstream Out( argv[2] );
	
	Out << "// " << Symbol << " (" << FileName << ") - Generated by Bin2C " VERSION " //" << endl;
	Out << "extern const unsigned " << Symbol << "_Size;" << endl;
	Out << "const unsigned " << Symbol << "_Size = " << (File->Size) << ";" << endl;
	Out << endl;
	Out << "extern const char " << Symbol << "[];" << endl;
	Out << "const char " << Symbol << "[] = {";
	
	int NextLine = 0;
	for ( int idx = 0; idx < File->Size; idx++ ) {
		if ( NextLine-- == 0 ) {
			NextLine = 16;
			Out << "\n\t";			
		}
		
		Out << (int)File->Data[idx] << ", ";
	}
	
	Out << endl << "};" << endl;
	
	
	// Close Output File //
	Out.close();
	
	// Done with File //
	delete_DataBlock(File);

	return 0;	
}
